# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f02adb0d6f930546f293e7ca8826a0dff779cf63630a4e3d772f77f5314ea1b2d2f70c3c30fb90dba15d7619277f882993d5cc1177512c98d4038b8ebc236222

test:
  secret_key_base: dd7ed04e6000b7a0593cd4f5bc4eb4312d5c74ff178e775071c2afda3be85a84a04cd332ba961a3c30c8d38febdf4da61143473df0f5a9e71150c8abdd4abe6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
